### ISSUE TITLE
Features for Tinyfoot

### ISSUE THREAD

**Issue by amnore** [Yashraj19/cse210-tinyfoot-team07#3]
The prototype is very primitive, and we need to add features. A good starting point is for it to match [bigfoot.js](https://github.com/lemonmade/bigfoot) feature-wise.

Missing features:

- [x] Click on the background to dismiss popups #7 
- [x] Popup and popdown animations
- [x] Numbering #10 
- [x] Placing popup at the bottom

I think some of these features also needs CSS work. @haitianxu2024

**Comment by haitianxu2024** [comment]
Finished the Bottom pop up style
